return {
  {
    "goolord/alpha-nvim",
    opts = function(_, opts) -- override the options using lazy.nvim
      opts.section.header.val = { -- change the header section value
        "    My Custom ",
        " Dashboard Header",
        "                  .   'dd,.'xKKx'.,dd'   .                  ",
        "                 ';;;:kXNKO0XNNX0OKNXk:coc'                 ",
        "            ,o:'',;:oOXNNNN0occdKNNNNNXN0l;'':o,            ",
        "            :dl;;;;:clk0O0Xx. .,kX0OKXNN0l;;:lx:            ",
        "       .lko;,;;;;;;;;,,,..:xOkkOx;...,:odc;;;;:;:dkl.       ",
        "        ckxc;;;;;;,''''..  .;cc,        .,:::::::oxc.       ",
        "    'odlclool:;;;;,''''''..              ,::::::::::ldo'    ",
        "    .xXOololl:;;;;,''''''''.             ,:::::::::ckXx.    ",
        "  ';ckXOoolc;:::;;,,''''''''.            ,:::::::::ckXkc;'  ",
        " .oXNNXOdoc:;;:::;;,'''''''''...         ,:::::::::ckXNNXd. ",
        "  'xXXOocloc:;;:::;,,,,,'',,,,,'.        ,cccccccccco0NXx'  ",
        ",okKNXo,;cooc:::::;'',,,,,,,,,,,'.       ,ccccccccc:;dXNKko,",
        ",xKNNNKxooolc:::::'..',,,,,,,,,,,,..     ,ccccccccccdKNNNKx,",
        " ,kXNNXklc::::::::,  ..,,,,,,,,,,,,'.    ,ccccccccclkXNNXk, ",
        "d0XNNNXkc:::::::::,    .,,,,,,,,,,,,,.   ;cccccclcclkXNNNX0d",
        ",o0NNNXkc:::::::::,     .',,,,,,,,,,,,...;llllllllloOXNNN0o;",
        " ;OXNNN0occccccccc,      .',,;,,,,,,,,,'';lllllllllo0NNNNO; ",
        ":0XNNNNKxccccccccc,        .,;;;;;;,;;;;;:lllllllllxXNNNNXO:",
        ".':kXNNN0occcccccc,         .,;;;;;;;;;;;:cllllllld0NNNXk:'.",
        "  :ONNNNXOoccccccc,          ..';;;;;;;;;:ccllllld0XNNNNO:  ",
        " .lkOKNNNX0dlclclc,             ';;;;;;;;:cccllox0XNNNKOkl. ",
        "    .dXNNNNKkolooo:.             .,;;;;;:lolllokKNNNNXd.    ",
        "    ,OXXXNNNXK000KO,              .,;;;:d0K0000XNNNXXXO,    ",
        "    .',,dXNNNX0xdOKd.              .';:l0Kkdx0NNNNXd,,'.    ",
        "       .oXXXXX0kxOX0l..             .;lkXKkdkKNXXXXo.       ",
        "        ,:;,dXNXXNNNXKOxolc::;;;:cloxOXXNNXXNNXd,,:,        ",
        "            cK0kkKNNNNNNNNNNNNNNNNNNNNNNNNKkk00c            ",
        "            .'. .dNXOkKNNNXXNNNNNNNNNKkOXNd. .'.            ",
        "                 'c;..cKKd:o0NN0o:dKKc..;c'                 ",
        "                      .lc. .l00l. .cl.                      ",
      }
    end,
  },
}
